[tensor] scsi: ufs: remove unused function ufshcd_compl_tm
/drivers/scsi/ufs/ufshcd.c:6659:13: error: unused function 'ufshcd_compl_tm' [-Werror,-Wunused-function]
static bool ufshcd_compl_tm(struct request *req, void *priv, bool reserved)
            ^
1 error generated.

Signed-off-by: krazey <admin@krazey.de>